package common

const (
	FamilyName = "ext4_chain"
	GroupID    = 6
)

const (
	EXT4_CHAIN_CMD_SETPID uint8 = iota
	EXT4_CHAIN_CMD_SETATTR_REQUEST
	EXT4_CHAIN_CMD_SETATTR_RESPONSE
	EXT4_CHAIN_CMD_GETATTR_REQUEST
	EXT4_CHAIN_CMD_GETATTR_RESPONSE
)

const (
	EXT4_CHAIN_ATTR_UNSPEC uint16 = iota
	EXT4_CHAIN_ATTR_UID
	EXT4_CHAIN_ATTR_GID
	EXT4_CHAIN_ATTR_ATIME
	EXT4_CHAIN_ATTR_MTIME
	EXT4_CHAIN_ATTR_CTIME
	EXT4_CHAIN_ATTR_MODE
	EXT4_CHAIN_ATTR_INO
	EXT4_CHAIN_ATTR_STATUS_CODE
)

const (
	EXT4_CHAIN_TIME_ATTR_SEC uint16 = iota
	EXT4_CHAIN_TIME_ATTR_NSEC
)
