package common

const FamilyName = "ext4_blockchain"

const (
	EXT4B_CMD_SETPID uint8 = iota
	EXT4B_CMD_SETATTR_REQUEST
	EXT4B_CMD_SETATTR_RESPONSE
	EXT4B_CMD_GETATTR_REQUEST
	EXT4B_CMD_GETATTR_RESPONSE
)

const (
	EXT4B_ATTR_UNSPEC uint16 = iota
	EXT4B_ATTR_UID
	EXT4B_ATTR_GID
	EXT4B_ATTR_ATIME
	EXT4B_ATTR_MTIME
	EXT4B_ATTR_CTIME
	EXT4B_ATTR_MODE
	EXT4B_ATTR_INO
	EXT4B_ATTR_STATUS
)

const (
	EXT4B_TIME_ATTR_SEC uint16 = iota
	EXT4B_TIME_ATTR_NSEC
)
